name = "mini-sigame-api"
main = "./src/index.ts"
compatibility_date = "2023-04-05"
account_id = "1f507c7933d231cc8051d23050bda6ab"
node_compat = true

route = { pattern = "api.minisi.krolebord.com", custom_domain = true }

kv_namespaces = [
  { binding = "SIGAME_KV", id = "7ad06ba0726343cd9131245541ac230b", preview_id="7ad06ba0726343cd9131245541ac230b" }
]

[[r2_buckets]]
binding = "SIPACKS"
bucket_name = "sigame"
preview_bucket_name = "sigamelocal"

[durable_objects]
bindings = [
  { name = "SIGAME_LOBBY", class_name = "MiniSigameLobby" }
]

[[migrations]]
tag = "si-1.0"
new_classes = ["MiniSigameLobby"]
